### ISSUE TITLE
apt-get update failing with 1.70

### ISSUE THREAD

**Issue by stonier** [rust-lang/docker-rust#149] opened 2023-06-03 21:36 UTC
**Fails**

* `./Dockerfile`

```
FROM rust:1.70-bullseye-slim
RUN apt-get update
```
* Docker command
```
docker build --pull -t rust-zen:${{ env.TAG }} ./
```
* Where: in a github action
* Docker version 23.0.1, build a5ee5b1
* Error Code: 159

-----

**Works**

* `rust:1.70-slim-bullseye` locally (NB: same docker version)
* `rust:1.69-slim-bullseye` locally and in github actions
* `rust:1.69-slim-bullseye` locally and in github actions
* `debian:bullseye-slim` locally and in github actions

**Comment by CommanderStorm** [comment] 2023-06-05 12:29
@stonier is this a duplicate of #147 ?
I.e. is your platform locally different from the one in `gha`?

**Comment by stonier** [comment] 2023-06-09 15:59
> @stonier is this a duplicate of https://github.com/rust-lang/docker-rust/issues/147 ? (is this resolved by the release yesterday?)

It is resolved, but whether it was the same issue or not, I'm not sure. My builds seem to be able to retrieve `1.70-slim` images, they just couldn't run apt-get internally:

```
Run docker build --pull -t rust-zen:rust1.70.0-bullseye --build-arg NAME=rust1.70.0-bullseye --build-arg RUST_VERSION=1.70.0 ./rust_docker_images/bullseye
  docker build --pull -t rust-zen:rust1.70.0-bullseye --build-arg NAME=rust1.70.0-bullseye --build-arg RUST_VERSION=1.70.0 ./rust_docker_images/bullseye
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DEBIAN_VERSION: bullseye
    RUST_VERSION: 1.70.0
    RUST_MAJOR_VERSION: 1
    RUST_MINOR_VERSION: 70
    DEBS_DEVEL: " bash bash-completion ca-certificates curl git graphviz less sudo ssh wget zsh vim wget iputils-ping iproute"
    DEBS_X11_GL: " libasound2-dev libudev-dev libx11-dev x11-xserver-utils mesa-utils libvulkan1 libvulkan-dev vulkan-tools libegl1 libgles2"
    TAG: rust1.70.0-bullseye
    ALIAS1: rust-bullseye
    ALIAS2: rust1.70-bullseye
#1 [internal] load .dockerignore
#1 transferring context:
#1 transferring context: 2B done
#1 DONE 0.1s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 

... 

FROM docker.io/library/rust:1.70-bullseye@sha2

...

#4 sha256:3bc99574da1b848024a10376669ee66fb0f5cadf58dd70663146d99ff8c16853 1.38kB / 1.38kB done
#4 sha256:1a0d3356018e75ca6a5a4c4a725230d86524408ca3a85bf7c2531edb4784ba63 6.09kB / 6.09kB done
#4 sha256:c377769761bd9f2bd79d27a4f6dfa29be1047f4e6e8df1653027ef5262e020bb 0B / 56.03MB 0.1s
#4 sha256:7c7401352be23d579ae1a3fd7882019c6fafadc0107273c644aa11e80739ab05 0B / 16.26MB 0.1s
#4 sha256:ff1e1a575fbf0c0e43cb8558b329a853703d6808c204c079d2823d91a9224f34 0B / 55.92MB 0.1s

...

#4 extracting sha256:d9d4555d713a234070b62c9ea8ad089d3ad12be602477caa6fe900066f25bf7b
#4 extracting sha256:d9d4555d713a234070b62c9ea8ad089d3ad12be602477caa6fe900066f25bf7b 2.9s done
#4 DONE 12.4s

#5 [2/9] RUN apt-get update
#5 ERROR: process "/bin/sh -c apt-get update" did not complete successfully: exit code: 159
------
 > [2/9] RUN apt-get update:
------
Dockerfile:25
--------------------
  23 |     ################################################################################
  24 |     
  25 | >>>  RUN apt-get update
  26 |      RUN apt-get update && apt-get install -y --no-install-recommends \
 |         # development
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update" did not complete successfully: exit code: 1[59]
```

> I.e. is your platform locally different from the one in gha?

Only marginally:

* Local: `Ubuntu 20.04.2`
* GHA: `20.04.5`

**Comment by stonier** [comment] 2023-06-09 16:00
Closing this ticket since it's now working.

**Comment by CommanderStorm** [comment] 2023-07-03 10:04
@stonier I think you forgot to click "close"

**Closed** 2023-07-05 13:22 UTC
